apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testnewperms-oct25 
  janus-idp.io/tekton: testnewperms-oct25
  backstage.io/kubernetes-id: testnewperms-oct25
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: testnewperms-oct25
resources: 
- application-dev.yaml