---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testnewperms-oct25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testnewperms-oct25 
  name: testnewperms-oct25
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi