apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testnewperms-oct25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testnewperms-oct25 
  name: testnewperms-oct25
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testnewperms-oct25 
    weight: 100 
  wildcardPolicy: None
